### ISSUE TITLE
Character multiplication when typing a custom question to Duo Explained on Chrome desktop

### ISSUE THREAD

**Issue by joaogenio** [digas99/duo-explained#31]
### Context

During lesson, before answering

### Issue Description

When I'm presented with a question and attempt to type a custom question for Duo Explained (ChatGPT), any character that I type suffers a strange behavior. As seen in the image below, some characters get multiplied and possibilly mixed up (see the 'a' character in between the 'w' characters).

![image](https://github.com/user-attachments/assets/94a706bb-e892-4a2a-9de8-7621ddd1a780)

**Chrome desktop**: 130.0.6723.117

### Challenge Data Object

```json
{
  "content": {
    "sentence": "My friend has a car.",
    "answer": [
      ""
    ],
    "wordBank": [
      "친구는",
      "자동차가",
      "자다",
      "지훈",
      "고마워",
      "지내",
      "있습니다"
    ]
  },
  "wrapper": {},
  "exercise": "Write this in Korean",
  "type": "translate",
  "language": {
    "target": "ko",
    "source": "en",
    "ui": {
      "document": "en",
      "client": {
        "main": "en-US",
        "options": [
          "en-US",
          "pt-PT",
          "pt",
          "en"
        ]
      }
    }
  }
}
```

### Browser

Chrome

### Extension Version

v0.0.1.3

### Target Language

Korean

### Explain Button

- [X] Was the Explain button enabled?

### Code of Conduct

- [X] I agree to abide by this project's Code of Conduct.

**Comment by digas99** [comment]
Commit cce51ca3e149d84a870e09aa622a52d28e84a407 closes this (v0.2.0)
