### ISSUE TITLE
Explanation has the context of the previous exercise when disabling and enabling during a lesson

### ISSUE THREAD

**Issue by joaogenio** [digas99/duo-explained#32]
### Context

During lesson, before answering

### Issue Description

During a lesson, I tried to disable the extension to see if the Duo Explained features would remain accessible until the end of the lesson, which it seemed they did, because none of the UI elements disappeared nor changed. When advancing to the next question, I enabled the extension again and tried using the Explain feature, but it gave me the explanation for the previous exercise.

As you can see in the image below, the explanation has nothing to do with the current exercise:

![image](https://github.com/user-attachments/assets/a2067a3d-67d5-42b4-a17c-ee30f411420d)

### Challenge Data Object

```json
{
  "content": {
    "sentence": "My friend has a car.",
    "answer": [
      ""
    ],
    "wordBank": [
      "친구는",
      "자동차가",
      "자다",
      "지훈",
      "고마워",
      "지내",
      "있습니다"
    ]
  },
  "wrapper": {},
  "exercise": "Write this in Korean",
  "type": "translate",
  "language": {
    "target": "ko",
    "source": "en",
    "ui": {
      "document": "en",
      "client": {
        "main": "en-US",
        "options": [
          "en-US",
          "pt-PT",
          "pt",
          "en"
        ]
      }
    }
  }
}
```

### Browser

Chrome

### Extension Version

v0.0.1.3

### Target Language

Korean

### Exercise Type

translate

### Explain Button

- [X] Was the Explain button enabled?

### Code of Conduct

- [X] I agree to abide by this project's Code of Conduct.

**Comment by joaogenio** [comment]
I think this will be ease to replicate. Here I enabled the extension during a question, and the "Explain" feature only turned on after i answered the question.

The effect here seems a bit different from this issue's but maybe still similar enough:
- ChatGPT's first phrase refers to the lesson's previous question.
- Then it processes the my answer to the current question and says it is wrong because it still thinks the question is from the previous exercise.
- Finally, it roasts me 😭 /s

![image](https://github.com/user-attachments/assets/9544aef3-03fa-4981-a41c-fa1003f56f5c)

**Comment by andreclerigo** [comment]
This issue happened because the Challenge Data was not being fetched when the extension was enabled. The same will happen when a user tries to get an explanation after already answering it, programmatically the solution will be the same. We'll fix that in a future commit.
